// (C) 1992-2017 Intel Corporation.                            
// Intel, the Intel logo, Intel, MegaCore, NIOS II, Quartus and TalkBack words    
// and logos are trademarks of Intel Corporation or its subsidiaries in the U.S.  
// and/or other countries. Other marks and brands may be claimed as the property  
// of others. See Trademarks on intel.com for full list of Intel trademarks or    
// the Trademarks & Brands Names Database (if Intel) or See www.Intel.com/legal (if Altera) 
// Your use of Intel Corporation's design tools, logic functions and other        
// software and tools, and its AMPP partner logic functions, and any output       
// files any of the foregoing (including device programming or simulation         
// files), and any associated documentation or information are expressly subject  
// to the terms and conditions of the Altera Program License Subscription         
// Agreement, Intel MegaCore Function License Agreement, or other applicable      
// license agreement, including, without limitation, that your use is for the     
// sole purpose of programming logic devices manufactured by Intel and sold by    
// Intel or its authorized distributors.  Please refer to the applicable          
// agreement for further details.                                                 

// Generated by Intel(R) HLS Compiler, Version 17.1.0 Build 590

/////////////////////////////////////////////////////////////////
// MODULE resize_internal
/////////////////////////////////////////////////////////////////
module resize_internal
(
   input logic clock,
   input logic resetn,
   // AVST original_image
   input logic original_image_valid,
   output logic original_image_ready,
   input logic [31:0] original_image_data,
   // AVST resized_image
   output logic resized_image_valid,
   input logic resized_image_ready,
   output logic [31:0] resized_image_data,
   input logic [31:0] ratio,
   input logic [31:0] rows,
   input logic [31:0] cols,
   input logic start,
   output logic busy,
   output logic done,
   input logic stall
);
   // INST resize_internal of resize_function_wrapper
   resize_function_wrapper resize_internal
   (
      .clock(clock),
      .resetn(resetn),
      // AVST avst_iord_bl_original_image
      .avst_iord_bl_original_image_valid(original_image_valid),
      .avst_iord_bl_original_image_ready(original_image_ready),
      .avst_iord_bl_original_image_data(original_image_data),
      // AVST avst_iowr_bl_resized_image
      .avst_iowr_bl_resized_image_valid(resized_image_valid),
      .avst_iowr_bl_resized_image_ready(resized_image_ready),
      .avst_iowr_bl_resized_image_data(resized_image_data),
      .ratio(ratio),
      .rows(rows),
      .cols(cols),
      .start(start),
      .busy(busy),
      .done(done),
      .stall(stall)
   );

endmodule

